name: Run Selenium CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Gradle
      run: chmod +x gradlew
      
    - name: run all cucumber selenium test case
      run: ./gradlew cucumber
      
    - name: Upload artifact archive test result
      uses: actions/upload-pages-artifact@v3.0.0
      if: always()
      with:
        name: Cucumber Report
        path: report
        
    - name: Deploy to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_DIR: report
